language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install: 
    - "python setup.py install"
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coveralls --use-mirrors"
script: "coverage run --source=hn setup.py test"
script:
    - nosetests -v --with-coverage --cover-package=hn
after_success: "coveralls"
notifications:
  email: false